name: Taryn Hovenkamp
repo_names:
  - DreamJournal
  - SweetDreams
11-models-from-data: 
  - https://github.com/tarynmh/ATLAS-iOS-Fall-22/tree/main/ModelsTest

10-ux-ui-criticism:
  - https://www.youtube.com/watch?v=HwlW8_EoEKA

project-check-in-1:
  - https://github.com/tarynmh/ATLAS-iOS-Fall-22/issues/2